name: multi_list_picker
description: A flutter package to select multiple or single item from a list picker.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: